import type { Metadata } from "next";
import "@/app/globals.css"
import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
import RootLayoutClient from "./RootLayoutClient";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bakool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        poppins.variable,
        poppins.className,
      )}
      suppressHydrationWarning
    >
      <body className="bg-background relative grid grid-cols-1 md:grid-cols-[auto_1fr] grid-rows-[auto_1fr] h-screen ">
        <RootLayoutClient>
          {children}
        </RootLayoutClient>
      </body>
    </html>
  );
}
