import type { Metadata } from "next";
import "@/app/globals.css"
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
import ThemeProviders from "@/components/ThemeProviders";
import { cn } from "@/lib/utils";
import AosProvider from "@/lib/aos-provider";
import Sidebar from "./Sidebar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bakool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        poppins.variable,
        poppins.className,
      )}
      suppressHydrationWarning
    >
      <body className={`bg-background relative grid justify-center grid-cols-[auto_auto] grid-rows-[auto_1fr] min-h-screen overflow-x-hidden`}>
        <ThemeProviders>
          <AosProvider>
            <Navbar />
            <Sidebar />
            <main className="flex flex-col items-center flex-1 mb-12">
              {children}
            </main>
          </AosProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
