import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import Navbar from "../components/Navbar";
import ThemeProviders from "../components/ThemeProviders";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", poppins.variable, poppins.className)}
      suppressHydrationWarning
    >
      <body className="relative flex flex-col items-center min-h-screen overflow-x-hidden" >
        <ThemeProviders>
          <Navbar />
          <main className="mb-23 flex flex-col items-center flex-1">
            {children}
          </main>
          <Footer />
        </ThemeProviders>
      </body>
    </html>
  );
}
