import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
import Sidebar from "./sidebar";
import AdminGuard from "@/components/AdminGuard";
import { Header } from "./header";
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bakool",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        poppins.variable,
        poppins.className,
      )}
      suppressHydrationWarning
    >
      <body className="relative grid h-screen overflow-hidden bg-background grid-cols-[auto_1fr] gap-y-8 grid-rows-[auto_1fr]">
        <Sidebar />
        <Header />
        <main className="px-8 overflow-y-auto">
          <AdminGuard>{children}</AdminGuard>
        </main>
      </body>
    </html>
  );
}
