import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from 'next/font/google';
import { cn } from "@/lib/utils";
import Sidebar from "./sidebar";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Bakool",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", poppins.variable, poppins.className)}
      suppressHydrationWarning
    >
      <body className="bg-background relative flex flex-row min-h-screen overflow-x-hidden" >
        <Sidebar />
        <main className="flex-1 p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
