import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from 'next/font/google';
import { cn } from "@/lib/utils";
import Sidebar from "./sidebar";
import { Header } from "./header";
import layout from "./layout.module.css"

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Bakool",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", poppins.variable, poppins.className)}
      suppressHydrationWarning
    >
      <body className={`relative grid min-h-screen overflow-x-hidden bg-background grid-cols-[auto_1fr] grid-rows-[auto_1fr]`} >
        <Sidebar />
        <Header />
        <main className="px-8 pb-8">
          {children}
        </main>
      </body>
    </html>
  );
}
